/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../common";

export interface DkimVerifierInterface extends utils.Interface {
  functions: {
    "keys()": FunctionFragment;
    "verifySignature(bytes,bytes,string,string,string)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "keys" | "verifySignature"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "keys", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "verifySignature",
    values: [BytesLike, BytesLike, string, string, string]
  ): string;

  decodeFunctionResult(functionFragment: "keys", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifySignature",
    data: BytesLike
  ): Result;

  events: {};
}

export interface DkimVerifier extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: DkimVerifierInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    keys(overrides?: CallOverrides): Promise<[string]>;

    verifySignature(
      data: BytesLike,
      signature: BytesLike,
      domain: string,
      selector: string,
      hashAlgo: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  keys(overrides?: CallOverrides): Promise<string>;

  verifySignature(
    data: BytesLike,
    signature: BytesLike,
    domain: string,
    selector: string,
    hashAlgo: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    keys(overrides?: CallOverrides): Promise<string>;

    verifySignature(
      data: BytesLike,
      signature: BytesLike,
      domain: string,
      selector: string,
      hashAlgo: string,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    keys(overrides?: CallOverrides): Promise<BigNumber>;

    verifySignature(
      data: BytesLike,
      signature: BytesLike,
      domain: string,
      selector: string,
      hashAlgo: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    keys(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    verifySignature(
      data: BytesLike,
      signature: BytesLike,
      domain: string,
      selector: string,
      hashAlgo: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
