/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  SHA1,
  SHA1Interface,
} from "../../../../@ensdomains/solsha1/contracts/SHA1";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "bytes32",
        name: "x",
        type: "bytes32",
      },
    ],
    name: "Debug",
    type: "event",
  },
] as const;

const _bytecode =
  "0x6080806040523460175760119081601d823930815050f35b600080fdfe600080fdfea164736f6c6343000813000a";

type SHA1ConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: SHA1ConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class SHA1__factory extends ContractFactory {
  constructor(...args: SHA1ConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(overrides?: Overrides & { from?: string }): Promise<SHA1> {
    return super.deploy(overrides || {}) as Promise<SHA1>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: string }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): SHA1 {
    return super.attach(address) as SHA1;
  }
  override connect(signer: Signer): SHA1__factory {
    return super.connect(signer) as SHA1__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): SHA1Interface {
    return new utils.Interface(_abi) as SHA1Interface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): SHA1 {
    return new Contract(address, _abi, signerOrProvider) as SHA1;
  }
}
